version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: denuncia_db
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file:
      - ../backend/.env.example
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
volumes:
  db_data:
